package com.theyavikteam.spainweather

enum class Province(val id:Int, val province:String, val idRegion: Int) {
    ALBACETE(1, "Albacete", 9)
    ,ALICANTE(1, "Alicante", 4)
    ,ALMERIA(1, "Almería", 1)
    ,ALAVA(1, "Álava", 7)
    ,ASTURIAS(1, "Asturias", 14)
    ,AVILA(1, "Ávila", 6)
    ,BADAJOZ(1, "Badajoz", 13)
    ,BALEARS_ILLES(1, "Illes Balears", 112)
    ,BIZKAIA(1, "Bizkaia", 7)
    ,BURGOS(1, "Burgos", 6)
    ,CACERES(1, "Cáceres", 13)
    ,CADIZ(1, "Cádiz", 1)
    ,CANTABRIA(1, "Cantabria", 16)
    ,CASTELLON(1, "Castellón", 4)
    ,CEUTA(1, "Ceuta", 18)
    ,CIUDAD_REAL(1, "Ciudad Real", 9)
    ,CORDOBA(1, "Córdoba", 1)
    ,CORUNA(1, "A Coruña", 5)
    ,CUENCA(1, "Cuenca", 9)
    ,GIPUZKOA(1, "Gipuzkoa", 7)
    ,GIRONA(1, "Girona", 2)
    ,GRANADA(1, "Granada", 1)
    ,GUADALAJARA(1, "Guadalajara", 9)
    ,HUELVA(1, "Huelva", 1)
    ,HUESCA(1, "Huesca", 11)
    ,JAEN(1, "Jaén", 1)
    ,LEON(1, "León", 6)
    ,LUGO(1, "Lugo", 5)
    ,LLEIDA(1, "Lleida", 2)
    ,MADRID(1, "Madrid", 3)
    ,MALAGA(1, "Málaga", 1)
    ,MELILLA(1, "Melilla", 19)
    ,MURCIA(1, "Murcia", 10)
    ,NAVARRA(1, "Navarra", 15)
    ,OURENSE(1, "Ourense", 5)
    ,PALENCIA(1, "Palencia", 6)
    ,PALMAS_LAS(1, "Las Palmas", 8)
    ,PONTEVEDRA(1, "Pontevedra", 5)
    ,RIOJA_LA(1, "La Rioja", 17)
    ,SALAMANCA(1, "Salamanca", 6)
    ,SANTA_CRUZ_TENERIFE(8, "Santa Cruz de Tenerife", 8)
    ,SEGOVIA(1, "Segovia", 6)
    ,SEVILLA(1, "Sevilla", 1)
    ,SORIA(1, "Soria", 6)
    ,TARRAGONA(1, "Tarragona", 2)
    ,TERUEL(1, "Teruel", 11)
    ,TOLEDO(1, "Toledo", 9)
    ,VALENCIA(1, "Valencia", 4)
    ,VALLADOLID(1, "Valladolid", 6)
    ,ZAMORA(1, "Zamora", 6)
    ,ZARAGOZA(1, "Zaragoza", 11)
}