package com.theyavikteam.spainweather

enum class Province(id:Int, name:String, idRegion: Int) {
    ALBACETE(1, "Albacete", 1)
    ,ALICANTE(1, "Alicante", 1)
    ,ALMERIA(1, "Almería", 1)
    ,ALAVA(1, "Álava", 1)
    ,ASTURIAS(1, "Asturias", 1)
    ,AVILA(1, "Ávila", 1)
    ,BADAJOZ(1, "Badajoz", 1)
    ,BALEARS_ILLES(1, "Illes Balears", 1)
    ,BIZKAIA(1, "Bizkaia", 1)
    ,BURGOS(1, "Burgos", 1)
    ,CACERES(1, "Cáceres", 1)
    ,CADIZ(1, "Cádiz", 1)
    ,CANTABRIA(1, "Cantabria", 1)
    ,CASTELLON(1, "Castellón", 1)
    ,CEUTA(1, "Ceuta", 1)
    ,CIUDAD_REAL(1, "Ciudad Real", 1)
    ,CORDOBA(1, "Córdoba", 1)
    ,CORUNA(1, "A Coruña", 1)
    ,CUENCA(1, "Cuenca", 1)
    ,GIPUZKOA(1, "Gipuzkoa", 1)
    ,GIRONA(1, "Girona", 1)
    ,GRANADA(1, "Granada", 1)
    ,GUADALAJARA(1, "Guadalajara", 1)
    ,HUELVA(1, "Huelva", 1)
    ,HUESCA(1, "Huesca", 1)
    ,JAEN(1, "Jaén", 1)
    ,LEON(1, "León", 1)
    ,LUGO(1, "Lugo", 1)
    ,LLEIDA(1, "Lleid", 1)
    ,MADRID(1, "Madrid", 1)
    ,MALAGA(1, "Málaga", 1)
    ,MELILLA(1, "Melilla", 1)
    ,MURCIA(1, "Murcia", 1)
    ,NAVARRA(1, "Navarra", 1)
    ,OURENSE(1, "Ourense", 1)
    ,PALENCIA(1, "PAlencia", 1)
    ,PALMAS_LAS(1, "Las Palmas", 1)
    ,PONTEVEDRA(1, "Pontevedra", 1)
    ,RIOJA_LA(1, "La Rioja", 1)
    ,SALAMANCA(1, "Salamanca", 1)
    ,SANTA_CRUZ_TENERIFE(1, "Santa Cruz de Tenerife", 1)
    ,SEGOVIA(1, "Segovia", 1)
    ,SEVILLA(1, "Sevilla", 1)
    ,SORIA(1, "Soria", 1)
    ,TARRAGONA(1, "Tarragona", 1)
    ,TERUEL(1, "Teruel", 1)
    ,TOLEDO(1, "Toledo", 1)
    ,VALENCIA(1, "Valencia", 1)
    ,VALLADOLID(1, "Valladolid", 1)
    ,ZAMORA(1, "Zamora", 1)
    ,ZARAGOZA(1, "Zaragoza", 1)
}